import type { JSX } from "react";

export const GirlsClub: React.FC<{ Image?: boolean, Caption?: string }> = (): JSX.Element => {
    return <div className="blog-message">
        <h4 className="font-bold">Girls’ Club Conference: School girls demand dignity and respect</h4>
        <p>As the South Africa Council for Educators (Sace), the regulatory body for teachers, meet with provincial education departments next week to address the recent scourge of sexual violence, bullying and abuse in schools, 200 school girls from across the country will gather in Cullinan to adopt a charter calling on duty bearers to uphold their right to safe quality education.</p>
        <p>ActionAid South Africa (AASA) is part of a consortium implementing a project that seeks to address Sexual Violence in Schools in South Africa (SeVISSA). In 2015, AASA and partner organisations conducted baseline research in SeVISSA-participating schools located in Gauteng and Limpopo. The findings, gathered from the voices and experiences of more than 400 learners, found that 45% of learners in Gauteng and 49% in Limpopo said boys force girls to have sex. One out of every five learners said they felt pressured by educators to have sex with them, while 9% of learners admitted to being raped.</p>
        <p>The latest figures, released by Basic Education Minister Angie Motshekga show an increase of reported cases of sex abuse by teachers, as well as physical assault, fraud and theft between the 2011 and 2016. Another study conducted by the Centre for Justice and Crime Prevention (CJCP) found that one in five pupils are exposed to sexual and physical violence in schools, the majority of victims being girls.</p>
        <p>Fatima Shabodien, AASA’s Director says the consequences of sexual violence and lack of safety in our schools are dire and far too costly to ignore.</p>
        <p>“The recent case of 30 girls being impregnated by teachers at a school in the Northern Cape demonstrates the extent of this crisis. It is unacceptable that the well documented daily experiences of violence in schools, perpetrated by both educators and school children, continue to fall on deaf ears. We need more than crisis management— concerted and consistent action by duty bearers is key to ensure our children can access safe and quality schooling.”</p>
        <p>From 2-4 October, as part of the SEVISSA programme and under the theme Educated Girls, Empowered womxn, AASA together with partner organisations— The Teddy Bear Clinic and Xihlobo Xa Ndivho as well as girls clubs from across the country will attend the annual Girl’s Club Conference. The purpose of the conference is to craft a space for learners to reflect and share among their peers, experiences of violence and barriers to education in South African schools.</p>
        <p>Since the conference in 2016, the girls’ clubs have collectively developed a charter highlighting the challenges they face in schools and their key demands to ensure they can access education without the fear of intimidation, harassment and sexual violence.</p>
        <p>The girls’ clubs will present and share the charter with duty bearers from the education sector attending the third and final day on Wednesday 4 October. Representatives from the Department of Education; Department of Social Development; the European Union; and other NGOs will be in attendance to receive their demands and to chart a way forward to urgently mitigate the unjust barriers to girls’ education.</p>
        <p>Sakhile Zungu, AASA’s SeVISSA Project Manager says it is high time we change the culture of violence against girls in schools.</p>
        <p>“It is inspiring to see these young womxn leading and affecting change, coming together to share struggles and to collectively claim their rights. I have no doubt that the charter will serve as an important advocacy tool both in their schools and within the education sector.”</p>
    </div>

}