import type { JSX } from "react";

export const Xenophobia: React.FC<{ Image?: boolean, Caption?: string }> = (): JSX.Element => {
    return <div className="blog-message">
        <p>With only 13 months since the national march against gender-based violence last year. The country is once again heading for a standstill regarding the state of violence against womxn and now including migrants, asylum seekers and refugees. On the 1st of August 2018 an estimate of over 50 000 womxn across the nation took to the streets demanding their right to live free from violence as enshrined in The Bill of Rights, Chapter 2 of the Constitution of the Republic of South Africa. Under the banner of #Thetotalshutdown, womxn shut the nation down. A memorandum of 24 demands was handed over to government on that day that outlined the demands of the womxn of the country. A year later we stand with over reported 26 cases of femicide in the month of August 2019 along. Most recently the murder of a university student at the university student Uyinene Mrwetyana killed brutally by a post office worker in broad daylight 100 meters away from the police station. The current state of normalised and accepted violence is unacceptable and is a constant fuel to the non-responsive position on this issue. 2019 and we are here again, seemingly as though we are in a depressing state of a dejavu. So, we mourn the state of the State</p>
        <p>We condemn the ongoing acts of violence targeted at migrants, asylum seekers and refugees. Evidenced by the ongoing raids on foreign owned businesses, targeted violence based on nationality and acts of harassment. As pan-Africanists, activists and fellow Africans, at ActionAid South Africa, we are appalled by the treatment of citizens of Africa in our country. We take a stand and are in support of all actions being taken by civil society to highlight this violence and we demand a change of this conversation by government.</p>
        <p>As part of over 50 civil society organizations in the sector, we are calling for a March on Friday13th September 2019 to the Johannesburg Stock Exchange in Sandton. We believe that the struggle to end gender-based violence and to end Xenophobia are connected. As systemic and structural violence against vulnerable people are connected. This connection often has underlying symptoms that can be directly linked to the socio-economic instability and gender inequality that is prevalent within that context. We are also acutely aware of the role that business in South Africa plays and its influence on government. As lives of people are continually affected and disenfranchised business runs unaffected nor interested in joining the call for the rights of people in South Africa to be realised. Business benefits from labour and monetary power of womxn, migrant, asylum seekers and refugees. We thus call on business to take on its ethical and social responsibility towards the people and communities it benefits from.</p>
        <p>We therefore call on government to acknowledge the attacks as XENOPHOBIC attacks targeted at migrants, asylum seekers and refugees. We call on government to retract its statement made by the Minister of Police saying that there will not be an end to “the police raids on migrant owned businesses in South Africa”. Such statements are inflammatory and continue to fuel animosity and violence against migrants.</p>
        <p>We call on business to take accountability of its role in the inequality within South Africa in so far as economic inequality is concerned On Friday the 13th September 2019, that we have entitled “the real black Friday”. We are again donning all black as a sign of our mourning and taking to the streets to march for an end to what is an unliveable situation.</p>
        <p>Join us either in marching or by standing in solidarity by dressing in all black.</p>
        <p>For further information contact:</p>
        <p>Lindelwe Nxumalo<br />
            Women’s Rights Manager<br />
            082 379 2416<br />
            Lindelwe.Nxumalo@actionaid.org</p>
    </div>

}