server_tokens off;

server {
    listen 3510;
    server_name actionaid.org.za;

    location / {
        root  /usr/share/nginx/html;
        index  index.html index htm;
        try_files $uri /index.html;
    }
} 