import type { JSX } from "react";

export const BlogTwoMessage: React.FC<{}> = ({ }): JSX.Element => {
    return <div className="blog-message">
        <p>Growing up in Diepkloof in Soweto where I spent a lot of my childhood and teenage years in the family of 15 children in my grandmother’s house. Where most of my family members who were living at the time were womxn. I was raised by my aunts. My mother was a domestic worker who worked in white suburban areas in the city looking after white people’s kids. As a child, it was difficult to understand why a woman would leave her own kids and go and look after other people’s children. But as I grew, I begin to understand why. she had to do that so that the family could have a meal on the table every day for all 15 of us at that time.</p>
        <p>During those times domestic violence was normal every Friday there was a woman screaming being brutalized by her boyfriend in the street. This behavior was normalized in that even during that era when we were teenagers, starting to date, when a girl didn’t want to talk to you or basically humiliated her for you as a guy to protect your so-called ego in the presence of your friends.</p>
        <p>I remember at some point during those days every Friday I would make sure that when I get home after school. In the afternoon I would go to the bus stop to wait for my mom so that I can accompany her home. This was because I wouldn’t want her to be the victim of verbal abuse or rape. Like many other in the township.</p>
        <p>Today we hear and read on social media and traditional media messages directed at men that carry patricial undertones such” imagine if this was your sister being bitten raped and killed” wait let’s stop there these sentiments are very problematic because. patriarchy teaches us a woman’s value is mostly in relation to the role she plays for a man. Rape is terrible. You don’t need to imagine the horror of it happening to someone “yours” if you understand womxn are, well, people.</p>
        <p>I had an interesting conversation with one of the members of (WAMUA) during a conference that was held in Mokopane. Her name was Princess from Mpumalanga. Princess is women’s rights activists who have been in the for forefront in fighting for women’s rights in mining-affected communities. Princess and I had a very long conversation around why a need for men is there to constantly prove themselves that they’re feminist. Why they can just be allies?</p>
        <p>This conversation probe certain questions and provided me with some light on what really the position of male bodies in the feminism movement . And why men can’t be feminist. Patriarchy has placed men at the top of the social hierarchy and validated their ideas, their concerns, their voice. womxn and other marginalized people have been silenced, questioned, doubted, and invalidated for centuries. Therefore, it is very suspicious when a man who has been socialized to oppress now claim wokeness without scrutiny. It is not enough for a man to join the feminist movement by only believing that the world is unfair to womxn. Therefore, men must be subjected to questioning this belief. And it shouldn’t be a woman who teaches a man about the principles of feminism. It should be a man that leads the educational process of unlearning the toxic patriarchal and misogynistic values. In that way, I think that the process of abandoning toxic male privilege begins to take shape. Men can’t be feminist because in some way feminism is a lived a experience. For example, a white person who stands with black in their struggle doesn’t make them black.</p>
        <p>I am learning to understand as a male who now regards himself as a ( FEMALLY) “someone who supports women’s rights and recognize that every woman is a human with equal worth. I used to call my self a feminist but that changed because feminism is a lived experience now as a male I can’t claim that I face the same injustices as a female comrade by being female. I can be an ally a “FEMALLY” in the feminist movement, not a feminist.</p>
    </div>
}