import type { JSX } from "react";

export const SorryNoJob: React.FC<{}> = ({ }): JSX.Element => {
    return <div className="blog-message">
        <p>I went to visit a group of young people who we work with in Orange Farm under Activista . My heart felt into cracks when me and the Activista team listened to their stories on how unemployment affect their daily lives. Most of them say we apply for jobs but its difficult to even pass an interview if you don’t know someone inside and most say you use your last cent to go to the internet searching for jobs you apply but you never a get a response when you Actively go out looking for a job you are told “sorry, no job”</p>
        <p>Unemployment has become almost pandemic over the past few years, and the youth are feeling the brunt of the problem. According to Stats South Africa, 63% of youth (people younger than 25-years-old) are unemployed. The overall unemployment rate in South Africa fell to 25% in 2015, a decrease from 35% in previous years. However, this decrease in unemployment does not take into account issues related to decent work and the fluctuating numbers of short-term contract work.
            A study of 180 countries published by the International Labor Organization estimates that in 2015, full-time employment represents less than one in four jobs. In South Africa, between 25% and 50% of workers are estimated to have temporary contracts, which mean that the calculated percentage of those who are employed might be lower than Stats SA figures suggest. The government tried putting structures in place such as the National Youth Development Agency (NYDA) and other initiatives that would help to curb unemployment, but these initiatives have not tackled the causes of unemployment, poverty and inequality.</p>
        <p>The national budget released by the treasury a few weeks ago shows that out of a total budget of R717.7 million, the NYDA was R409.8 million. But, just under half of that goes to job creation for the youth, when more than half (55%) of the working population are youth, while the other 57% of that budget goes to pay NYDA salaries!
            This indicates on how the issue of youth unemployment is not so important to our government. The government needs to show seriousness to the issue of youth unemployment. As a young person in South Africa you only have one out of four chances in getting a permanent job. There is a concern in the increase rate of unemployment of black Africans with tertiary education. It has more than doubled, from “8% to 19%,” Stats SA said. The unemployment rate among the white population group – ranging between 4.1% in 2008 and 7.3% in 2014 – is the lowest of all the population groups by a large margin, the data found. In 2014, Black Africans account for 79.3% of the working age population but they are under -represented among the employed (73.0%) and over-represented among the unemployed (85.7%) and the not economically active population is (83.3%). The issue of unemployment is not only about economics but it is also about race, gender and other inequalities the continues exclusion of these groups in our economics spells out that we our government is not thoughtful about bridging the gap between the poor and the rich.</p>
        <p>Sources STATS SA reported by the Statistics South Africa.</p>
    </div>
}