import type { JSX } from "react";

export const TotalShutDown: React.FC<{}> = ({ }): JSX.Element => {
    return <div className="blog-message">
        <p>I recall leaving the meeting excited over the planned activities (Total shutdown, Intimate partner violence, awareness on working with disabilities, Inequality launch). I couldn’t wait to change Women’s life’s forever in a month little did I know that the feminist gods had other plans in mind for me in August that will change my perspective and meaning of women’s month.</p>
        <h4 className="font-bold">1. The Total Shutdown</h4>
        <p>It was until the march I was looking for my fellow RAA members and me could not find them until I realized I am not my friends and I need to show up for myself and residues of abuse and I joined a group of womxn together with my amazing partner and we sang we screamed and we cried and I felt liberated until we sat down for the moment of silence and I was sitting next to Virginia Magwaza (mother, sister, human rights activist) and I was held we laughed and cried shared stories but she listened and that is the best gift and lesson I could have received and from now on I will take notice to other womxn really get to their needs.</p>
        <h4 className="font-bold">2. The Intimate partner violence</h4>
        <p>I needed to tell my story before telling other people’s tragedies I desired to heal my own wounds as I experienced a lot of GBV growing until my adult life, my dad used to abuse my mother physical abuse for years building up we assumed it was a norm and it was ok just because it was my dad who did it, both my sisters were abused and harassed by local gangsters in the area while growing up and they feared going out of the house and called for to be accompanied everywhere they went for their own protection thought I would learn they violence harms another person? Nope until I hit my then previous partner then I realised this GBV is all about power I needed to control her and she called for to fear me in order to respect me and do everything I called for her to do, not realizing that was not love, love could not beat her up and leave her in a pool of blood! That scene alone reminded me of my mother’s screaming for my dad to stop and this felt like someone has pulled up the main switch in my head and I woke up and walked away. I got myself some counseling and anger management classes, but I still suffer from anxiety most times because I can’t live with the guilt of harming another black womxn no matter what she did she did not get the wrath of my resentment. Most days I am gentle with myself and learning to communicate my insecurities and yes, I have been trying to reach out and apologize and safely say I am in a good space and will advocate or survivors of GBV as I know they don’t justify such cruelty</p>
        <h4 className="font-bold">3. Awareness of womxn living with disabilities</h4>
        <p>The event did not take place as it could not be just another event it needed to be eye opening and life changing, the person I consulted about the event wanted to have a dialogue while I wanted to walk a mile in their shoes, I wanted black womxn to think of their privileges and how disabled bodied womxn get through a day and until we have such a concept that will allow abled bodied womxn to experience a day in the shoes of a disabled womxn that event will wait. However, in the absence of the planned event we called in friends, comrades others strangers (as it was my first time meeting them) to a wine, cheese ladies talk feminists holding each other. Oh, I had not expected so much from an event the best of all I had planned as it was authentic no rehearsals it was sisters showing up for each other while sharing their daily life struggles with their kids, siblings or intimate partners. Tears flowed, hugs and kisses followed by song and that for me was contentment because while I thought the event won’t get off the ground a sister Charlene Harry kept reassuring me it will happen of feminist gods sent her my way on that day and she carried me through it all and that is the true sign of sisterhood Ndiyabulela Mbokodo.</p>
        <h4 className="font-bold">4. Inequality launch</h4>
        <p>Planning for this event changed my perspective on different jobs that womxn had to endure to make a living for themselves and their families, we interviewed womxn that work from Heineken and they shared their experiences from not having formal contracts, they cannot join unions and worse part sometimes they get paid months after they had worked making it impossible to survive under the minimum wage. The high rate of unemployed leads these womxn to work for companies that use them and work under unhealthy circumstances like Matshidiso Mofokeng who works or a company that builds transformers from scratch she has no contract and her working for hours by the number of transformers they have to manufacture, the shocking part of her work is having no formal training to handle the huge machinery she has to work with and the company has no medical insurance if you get cut you on your own and you cant report the manager as officially there is no paperwork to prove you are an employee of the company. They have written the report and the launch will take place in September and we hope that with the report Unions and the Government officials will stand up for women’s rights.</p>
        <p>Even though my month did not go according to plan but it could not have turned any better for me because I learned and unlearnt what it meant to show up for friends and family, I learned the true meaning of feminism is not only about marching and hailing slogans but its about spending the whole night as womxn chopping and cooking for a family tombstone the conversations around the fire about building family relations that older family members failed to do. I learned that friendships or sisterhood is not about posting pictures of Fb or about the calls but the Friday I was sick and Kumkani and Sakhile refused to take me home but instead made sure I stay around for the braai in the office, then I can safely say I never made it home that Friday I ended up at kumkani’s flat and let’s just say I had the best night of my life sharing space with beautiful womxn who changed my view on feminism Koketso and Sbongile that day I gained sisters in the struggle and that made my heart smile still in pain I grew and endured.</p>
        <p>I could not have been here if it was not because of my Manager Lindelwe Nxumalo she gives me so much life and she calls me her fire, she gives me free reign to dream even if she does not see it happening she lets me learn from my mistakes and I am certain she was brought my way by the feminists gods and I will forever be grateful for her teachings which led me to agree to facilitate sessions for the office of the premier in return boosted my confidence I could have never done everything without her super guidance.</p>
        <p>In conclusion, women’s month for me was an eye awakening as I had to live by my philosophy the feminism of Ubuntu, Ubuntu that recognizes that mama Ekhaya and not only for the woke and elite, I touched a lot of womxn and in return I felt blessed by their wisdom, courage, and willpower to push through this life thing and through it all I was not alone, my friend and life partner was there by my side she was there through the self-realisation, the tears of sadness and happiness she witnessed me grow from strength to strength and she held my hand through it all. Comrades Women’s month and that is the gift I will share with womxns around me and not make the month about events but it is about being there even if it is just to listen, or hold a hand I will show up……</p>
    </div>
}