import type { JSX } from "react";

export const YouthCourage: React.FC<{}> = ({ }): JSX.Element => {
    return <div className="blog-message">
        <h6>The search for equality, dignified employment and social justice</h6>
        <h4 className="font-bold">What’s the overarching problem/ causes</h4>
        <p>Youth unemployment is one of the biggest social injustices of our time. It affects young people from all walks of life – informal street sellers on the streets of Lagos to recently graduated university students in the cities of Europe. Youth unemployment is an everyday drudging reality for 73 million plus young men and womxn worldwide (ILO, 2013). It has an impact on health, education, family, resilience, and quality of life. It is a man-made disaster, which has ramifications not just for the young men and womxn directly affected, but also their families who they support, and in the long term – their community and national development.</p>
        <p>At the core of structural issues perpetuating and exacerbating youth unemployment (economic, social and political disempowerment) is the phenomenon of jobless growth. Economists define this as a prolonged period, where the economy (macro economy) as a whole improves, but the unemployment rate remains high or continues to increase. There is no mythical neo-liberal trickle down. This is particularly evident in sub Saharan Africa (SSA), where “in 2013, survey data from the Afrobarometer collected across 34 African countries stated that there was little change in poverty at the grassroots after a decade of growth. Furthermore, the ILO data show that SSA has the highest rate of vulnerable employment in the world (77.4 percent in 2013). Vulnerable employment is defined as unpaid family workers and own-account workers as a percentage of total employment. ”</p>
        <p>Big multinationals are creating growth for themselves and their shareholders only. Greed, fear, a lack of vision on collective growth are a few reasons for this. Concepts of social obligations/protection and respect for human rights might as well be a foreign language. But it is not enough to simply provide a job , they must be ‘decent jobs’. Many young citizens we support are demanding social protection, raising welfare issues and lack of benefits and future training, need for ombudsmens, open data, accountability forums for youth unemployment funds etc. They are angry at being pushed back. Of short term contracts, poor education, cronyism, patriarchy, patronage systems and not being listened to.</p>
        <h4 className="font-bold">Solutions</h4>
        <p>The alternative approach is a Human Rights Based Approach to economics, politics, the environment and society. For young people a vision where they have a holistic education, which matches skills needed in an evolving world: a dignified job that they have the skills to maintain, and continue to fight for. Whereby they can connect; collectivise and support the livelihood rights of other young people. Youth cannot really be “empowered” unless we challenge the power of those who are shutting their eyes, ears and minds to youth rights, and instead allow new ideas, solutions and humanity to be brought to the fore.</p>
        <p>Not only is this a moral obligation, but a long term development necessity. Not “only can poverty experienced in youth have implications across the life course of the young person, it can hinder the capacity of a young person to bounce back from deprivation suffered in childhood, and affect the long-term life chances of any dependents, including and especially the young person’s own children.”</p>
        <p>Inequality breeds more deprivation, poverty and disenchantment. A long term strategy and vision built with young people needs to go beyond the short termism of corporate culture based on appeasing shareholders. We have created a platform for some of our young partners to begin to present their alternative vision via social design processes . They are not to blame: they are not idle, incapable nor passive. But they are questioning, provocative, courageous and keen to contribute, build and re-imagine.</p>
        <p>[solutions will develop further as our analysis on youth unemployment does, but for now this is where we are i.e. we are not yet specifying where lots of jobs come from, rather shinning a light on structural causes creating increasing youth unemployment which is symptomatic of inequality/widening gap between haves and have nots. The above should also build in Antione (ways to strengthen agricultural jobs), Aggy (gender analysis), Sameer (public sector jobs are beneficial/stats), Tanvir (don’t ignore basic education – link to life cycle), Harjeet (stop environmental impact to safeguard jobs), Rick (manufacturing/services to expand)].</p>
        <h4 className="font-bold">What do we want decision makers to do</h4>
        <p>– Recognise that young men and womxn are not to blame for unemployment; rather its greed, fear, a lack of vision on collective growth. [or could say jobless growth, corporate short termism and reduced & weakened State provision].</p>
        <p>– Strengthen the role of the State: not only in terms of creating dignified jobs for diverse young womxn and men, but by ensuring accountability mechanisms to review/monitor youth employment funds are fit for purpose and include youth!</p>
        <p>– Ensure that job creation youth policy includes a gender anlaysis e.g. fulfilling employment for a young mother is different for a young male graduate.</p>
        <p>– Work with youth to develop better programmes and policy at design, implementation and review phases I order to provide dignified and fulfilling jobs (livelihoods).</p>
        <p>– Invest in youth development: because it’s a moral obligation, but also a long term development necessity. [children of jobless youth are likely to be trapped in cycle of poverty].</p>
    </div>
}